# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - curl --insecure -OL https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.6.1.zip
          - unzip sonar-scanner-2.6.1.zip
          - ./sonar-scanner-2.6.1/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.branch=c7c72c2d63d7a0e1da298dd2a1b4a8def283fcec
